name: Docker Compose

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-docker@v2.6.0
      with:
        compose-version: '2.0.0'

    - name: Build and run containers
      run: |
        docker compose up build